<x-app-layout>
    <x-slot name="header"><div class="flex items-center justify-between gap-3"><h2 class="text-lg font-semibold text-gray-900">{{ __('Warehouses') }}</h2><a href="{{ route('warehouses.create') }}" class="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-medium text-white hover:bg-indigo-700">{{ __('Add warehouse') }}</a></div></x-slot>
    <div class="mx-auto max-w-7xl space-y-6 py-12 sm:px-6 lg:px-8">
        @if(session('status'))<div class="rounded-lg bg-{{ session('status.type') === 'error' ? 'red' : 'green' }}-100 p-3 text-sm">{{ session('status.message') }}</div>@endif
        <form method="GET" class="flex items-center gap-3 rounded-lg bg-white p-4 shadow"><label class="inline-flex items-center gap-2 text-sm"><input type="checkbox" name="inactive" value="1" @checked($showInactive)> {{ __('Show inactive') }}</label><x-primary-button>{{ __('Filter') }}</x-primary-button><a href="{{ route('warehouses.index') }}" class="text-sm underline">{{ __('Reset') }}</a></form>
        <div class="overflow-x-auto rounded-lg bg-white shadow"><table class="min-w-full text-sm"><thead class="bg-gray-50 text-left"><tr><th class="px-4 py-3">Name</th><th>Code</th><th>Address</th><th>Products</th><th>Status</th><th></th></tr></thead><tbody class="divide-y">
        @forelse($warehouses as $warehouse)<tr><td class="px-4 py-3"><a href="{{ route('warehouses.show',$warehouse) }}" class="font-medium text-indigo-700">{{ $warehouse->name }}</a></td><td>{{ $warehouse->code ?: '—' }}</td><td>{{ $warehouse->address ?: '—' }}</td><td>{{ $warehouse->products_count }}</td><td>{{ $warehouse->is_active ? 'Active' : 'Inactive' }}</td><td class="px-4 py-3 text-right"><a href="{{ route('warehouses.edit',$warehouse) }}" class="text-indigo-600">Edit</a> <form class="inline" method="POST" action="{{ route('warehouses.destroy',$warehouse) }}" onsubmit="return confirm('Delete this warehouse?')">@csrf @method('DELETE')<button class="text-red-600">Delete</button></form></td></tr>
        @empty<tr><td colspan="6" class="px-4 py-6 text-gray-500">No warehouses yet.</td></tr>@endforelse</tbody></table></div><div>{{ $warehouses->links() }}</div>
    </div>
</x-app-layout>