<x-app-layout>
    <x-slot name="header"><div class="flex items-center justify-between"><div><h2 class="text-lg font-semibold text-gray-900">{{ $purchase->invoice_number }}</h2><p class="text-sm text-gray-500">{{ $purchase->supplier?->name }} · {{ $purchase->ordered_at->format('d M Y') }}</p></div><div class="flex gap-2">@if($purchase->status==='ordered')<form method="POST" action="{{ route('purchases.receive',$purchase) }}">@csrf<button class="rounded-lg bg-green-600 px-4 py-2 text-sm text-white">Receive goods</button></form>@endif @if(in_array($purchase->status,['ordered','received'],true))<form method="POST" action="{{ route('purchases.cancel',$purchase) }}" onsubmit="return confirm('Cancel this purchase and reverse received stock?')">@csrf<button class="text-sm text-red-600">Cancel</button></form>@endif</div></div></x-slot>
    <div class="mx-auto max-w-6xl space-y-6 py-12 sm:px-6 lg:px-8">
        {{-- Every purchase write (create, receive, cancel, delete) redirects here with
             `status` flashed. This view never rendered it, so those confirmations were
             written to the session and thrown away unread: the action succeeded and the
             user was told nothing. Same bug shape as the stock page. --}}
        @if (session('status'))
            @php($status = session('status'))
            <div role="{{ ($status['type'] ?? 'success') === 'error' ? 'alert' : 'status' }}"
                 class="rounded-lg p-3 {{ ($status['type'] ?? 'success') === 'error' ? 'bg-red-100 text-red-800' : 'bg-green-100 text-green-800' }}">
                {{ $status['message'] ?? '' }}
            </div>
        @endif

        <div class="grid gap-4 sm:grid-cols-4"><div class="rounded-lg bg-white p-5 shadow"><div class="text-sm text-gray-500">Status</div><div class="text-lg font-semibold">{{ ucfirst($purchase->status) }}</div></div><div class="rounded-lg bg-white p-5 shadow"><div class="text-sm text-gray-500">Warehouse</div><div class="text-lg font-semibold">{{ $purchase->warehouse?->name }}</div></div><div class="rounded-lg bg-white p-5 shadow"><div class="text-sm text-gray-500">Total</div><div class="text-lg font-semibold">{{ \App\Services\Money::format($purchase->total) }}</div></div><div class="rounded-lg bg-white p-5 shadow"><div class="text-sm text-gray-500">Outstanding</div><div class="text-lg font-semibold">{{ \App\Services\Money::format($purchase->invoice?->outstanding ?? $purchase->total) }}</div></div></div><div class="overflow-x-auto rounded-lg bg-white shadow"><table class="min-w-full text-sm"><thead class="bg-gray-50"><tr><th class="px-4 py-3">Product</th><th>SKU</th><th>Qty</th><th>Unit cost</th><th>Subtotal</th></tr></thead><tbody class="divide-y">@foreach($purchase->items as $item)<tr><td class="px-4 py-3">{{ $item->product_name }}</td><td>{{ $item->sku ?: '—' }}</td><td>{{ $item->quantity }}</td><td>{{ \App\Services\Money::format($item->unit_cost) }}</td><td>{{ \App\Services\Money::format($item->subtotal) }}</td></tr>@endforeach</tbody><tfoot class="border-t font-semibold"><tr><td colspan="4" class="px-4 py-3 text-right">Subtotal</td><td class="px-4 py-3">{{ \App\Services\Money::format($purchase->subtotal) }}</td></tr><tr><td colspan="4" class="px-4 py-3 text-right">Total</td><td class="px-4 py-3">{{ \App\Services\Money::format($purchase->total) }}</td></tr></tfoot></table></div></div>
</x-app-layout>