<x-app-layout>
    <x-slot name="header"><div class="flex items-center justify-between"><h2 class="text-lg font-semibold text-gray-900">{{ $pageTitle }}</h2><a href="{{ route('expenses.index') }}" class="text-sm underline">Back to expenses</a></div></x-slot>
    @php($amount = fn($v) => $v ? number_format($v/100,2,'.','') : '')
    <div class="mx-auto max-w-3xl py-12 sm:px-6 lg:px-8"><form method="POST" action="{{ $submitUrl }}" class="space-y-5 rounded-lg bg-white p-6 shadow">@csrf @if($expense->exists) @method('PUT') @endif
        <div class="grid gap-4 sm:grid-cols-2"><div><x-input-label for="description" :value="__('Description *')"/><x-text-input id="description" name="description" class="mt-1 block w-full" :value="old('description',$expense->description)" required/><x-input-error :messages="$errors->get('description')" class="mt-2"/></div><div><x-input-label for="amount" :value="__('Amount (Rp) *')"/><x-text-input id="amount" name="amount" type="number" min="0.01" step="0.01" class="mt-1 block w-full" :value="old('amount',$amount($expense->amount))" required/><x-input-error :messages="$errors->get('amount')" class="mt-2"/></div>
        <div><x-input-label for="category_id" :value="__('Category')"/><select id="category_id" name="category_id" class="mt-1 block w-full rounded-md border-gray-300"><option value="">No category</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id',$expense->category_id)==$category->id)>{{ $category->name }}</option>@endforeach</select></div>
        <div class="grid gap-4 sm:grid-cols-2"><div><x-input-label for="expense_date" :value="__('Date *')"/><x-text-input id="expense_date" name="expense_date" type="date" class="mt-1 block w-full" :value="old('expense_date',$expense->expense_date?->format('Y-m-d'))" required/></div><div><x-input-label for="payment_method" :value="__('Payment method')"/><select id="payment_method" name="payment_method" class="mt-1 block w-full rounded-md border-gray-300">@foreach(['cash','bank','transfer','qris','other'] as $method)<option value="{{ $method }}" @selected(old('payment_method',$expense->payment_method ?: 'cash')===$method)>{{ str($method)->headline() }}</option>@endforeach</select></div></div>
        <div><x-input-label for="notes" :value="__('Notes')"/><textarea id="notes" name="notes" rows="3" class="mt-1 block w-full rounded-md border-gray-300">{{ old('notes',$expense->notes) }}</textarea></div><x-primary-button>{{ $expense->exists ? __('Update expense') : __('Save expense') }}</x-primary-button>
    </form></div>
</x-app-layout>